### ISSUE TITLE
Notice: Trying to get property '' of non-object

### ISSUE THREAD

**Issue by thedf** [fivefilters/readability.php#12]
Hey there,

I am facing the following notices about getting properties of non-objects when using this library for articles from this [feed](http://www.einnews.com/rss/ut7oA_IwQCuEGNtD): 

```
Trying to get property 'length' of non-object in /PATH/vendor/fivefilters/readability.php/src/Readability.php on line 1514
Trying to get property 'textContent' of non-object in /PATH/vendor/fivefilters/readability.php/src/Readability.php on line 207
Trying to get property 'childNodes' of non-object in /PATH/vendor/fivefilters/readability.php/src/Readability.php on line 1506
```

**Comment by fivefilters** [comment]
Thanks for reporting this @thedf! The latest version (3.1.2) should fix it. Please let us know if you still have trouble with it.

**Comment by thedf** [comment]
Thanks for the quick fix and release. I will keep you in touch if I find any other problems.
