### ISSUE TITLE
Attempt to read property "length" on null in src/Readability.php on line 1514

### ISSUE THREAD

**Issue by thedf** [fivefilters/readability.php#15]
related to : #12 
Hey @fivefilters , we are getting this error instead in php8.1.
Attempt to read property "length" on null in /PATH/vendor/fivefilters/readability.php/src/Readability.php on line 1514

it's probably better to make the fix something like this :
`vendor/fivefilters/readability.php/src/Readability.php:1506 : $siblings = $parentOfTopCandidate->childNodes ?? [];`

Thanks for your attention on this !

**Comment by fivefilters** [comment]
Thanks for reporting this. Should have tested the earlier fix better.

It should now be fixed in [v3.1.4](https://github.com/fivefilters/readability.php/releases/tag/v3.1.4)

Using `?? []` would still have the same problem (no length property).
