### ISSUE TITLE
composer require not pulling latest package

### ISSUE THREAD

**Issue by ahpetrot** [fivefilters/readability.php#2]
**Package install in a clean directory**

~/Sites/package-test  composer require fivefilters/readability.php
Using version ^2.1 for fivefilters/readability.php
./composer.json has been updated
Running composer update fivefilters/readability.php
Loading composer repositories with package information
Updating dependencies
Lock file operations: 2 installs, 0 updates, 0 removals
  - Locking fivefilters/readability.php (v2.1.0)
  - Locking psr/log (1.1.4)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing psr/log (1.1.4): Extracting archive
  - Installing fivefilters/readability.php (v2.1.0): Extracting archive
1 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files

vi  the Readability file, and namespace are all incorrect . 

namespace andreskrey\Readability;

use andreskrey\Readability\Nodes\DOM\DOMDocument;
use andreskrey\Readability\Nodes\DOM\DOMElement;
use andreskrey\Readability\Nodes\DOM\DOMNode;
use andreskrey\Readability\Nodes\DOM\DOMText;
use andreskrey\Readability\Nodes\NodeUtility;
use Psr\Log\LoggerInterface;

Just to be sure I cleaned out composer cache and uninstalled and reinstalled.. Same issues.  

From composer this is broken.

**Comment by sommer-gei** [comment]
Hi @ahpetrot !

I think `v2.1.0` is the latest version from the original repo of [andreskrey/readability.php](https://github.com/andreskrey/readability.php).

So you may checkout the [_version_ `dev-master`](https://packagist.org/packages/fivefilters/readability.php#dev-master) to get the last changes.

Or you stay at `v2.1.0` and use this code:

```php
use andreskrey\Readability\Readability;
use andreskrey\Readability\Configuration;
use andreskrey\Readability\ParseException;
```

(But: I'ts currently a little bit confusing, yes. However, no new version is/was announced by @fivefilters …)

KR

**Comment by fivefilters** [comment]
Sorry for the confusion @ahpetrot, @sommer-gei is right, at the moment you'll have to rely on dev-master to run the latest changes in the repository. We'd been planning to roll out new versions of our own software to some users as a way to test the library in wider use. We've been too busy with other things so far, but that's still the plan. Then we'll know if we're ready for a new versioned release here.

**Comment by minthemiddle** [comment]
Just for reference (because I had to Google it as well…): Use `composer require fivefilters/readability.php:dev-master` to get the `dev-master`.

**Comment by fivefilters** [comment]
We've now added tags for the latest updates, so you should be able to use

`composer require fivefilters/readability.php`

or 

`composer require fivefilters/readability.php:3.1.0`
