### ISSUE TITLE
Call to undefined method DOMEntityReference::getAttribute()

### ISSUE THREAD

**Issue by phuclh** [fivefilters/readability.php#20]
```php
$readability = new Readability(new Configuration);
$readability->parse($html);
```
This is the HTML causes that error: `Call to undefined method DOMEntityReference::getAttribute()`

[test.html.zip](https://github.com/fivefilters/readability.php/files/11607436/test.html.zip)

**Comment by phuclh** [comment]
@fivefilters Any updates on it? Thank you!

**Comment by fivefilters** [comment]
@phuclh I cannot reproduce this using the HTML you supplied and the master branch. Please ensure you test with the master branch. If you still have the same problem, please provide some minimal code to reproduce the problem.

**Comment by phuclh** [comment]
@fivefilters Seems it doesn't throw that error with the latest version however it return `false` when I call `getContent` method, `getTitle()` still work correctly. Same HTML that I attached above.

```php
$readability = new Readability(new Configuration);
$readability->parse($html);

echo $readability->getContent(); // This return FALSE.
```

I also found another issue `Attempt to read property "nodeName" on null` with the below HTML.

[nodeName.html.zip](https://github.com/fivefilters/readability.php/files/11766736/nodeName.html.zip)

**Comment by fivefilters** [comment]
@phuclh `getContent()` worked fine on the HTML you provided in your first message when I tested. Which version of PHP are you using?

Could you please create a new issue for the `Attempt to read property "nodeName" on null` message. Please include your PHP version and code to reproduce the error.

**Comment by phuclh** [comment]
@fivefilters I am using PHP 8.2. I am going to create a new issue for it now.
