### ISSUE TITLE
Attempt to read property "nodeName" on null

### ISSUE THREAD

**Issue by phuclh** [fivefilters/readability.php#22]
I am using PHP 8.2 and get the exception: `Attempt to read property "nodeName" on null`.

Below is my code & the HTML.

```php
$readability = new Readability(new Configuration);
$readability->parse($html);

echo $readability->getContent();
```

[nodeName.html.zip](https://github.com/fivefilters/readability.php/files/11766736/nodeName.html.zip)

**Comment by phuclh** [comment]
Hi @fivefilters, have you had a chance to look at this? Thank you!

**Comment by phuclh** [comment]
@fivefilters Have you looked at it by any chance?

**Comment by fivefilters** [comment]
Sorry for the late reply. I wasn't able to reproduce this. If you still get the error, please include the line number in the code from the error message.
