### ISSUE TITLE
PHP Deprecated: dirname(): Passing null to parameter #1 ($path) of type string is deprecated

### ISSUE THREAD

**Issue by blat** [fivefilters/readability.php#23]
Hello,

I've some PHP Deprecated with some URLs

Here is my sample code:

```
$url = 'https://investor.cummins.com';
$html = file_get_contents($url);

$config = new fivefilters\Readability\Configuration();
$config->setFixRelativeURLs(true);
$config->setOriginalURL($url);

$readability = new fivefilters\Readability\Readability($config);
$readability->parse($html);
```

Current result: 
```
PHP Deprecated: dirname(): Passing null to parameter #1 ($path) of type string is deprecated in vendor/fivefilters/readability.php/src/Readability.php on line 842
PHP Deprecated: dirname(): Passing null to parameter #1 ($path) of type string is deprecated in vendor/fivefilters/readability.php/src/Readability.php on line 842
```
I'm using PHP 8.2.7 with fivefilters/readability.php v3.1.6.

This is not blocker, but I like clean logs ;)

Thanks!

**Comment by Markus-GS** [comment]
Modify line as follows:

           $pathBase = parse_url($url, PHP_URL_SCHEME) . '://' . parse_url($url, PHP_URL_HOST) . dirname(parse_url($url, PHP_URL_PATH) **?? ''**) . '/';

**Comment by fivefilters** [comment]
Thanks for reporting this @blat and for the fix @Markus-GS. Should be fixed in this commit https://github.com/fivefilters/readability.php/commit/c1f71912ca26448edfbcb577fe16ff8b27aadfba. Release out soon.

**Comment by fivefilters** [comment]
Fixed in https://github.com/fivefilters/readability.php/releases/tag/v3.1.7
