### ISSUE TITLE
League\\Uri\\Uri can throw Syntax errors

### ISSUE THREAD

**Issue by marcelklehr** [fivefilters/readability.php#24]
Please consider catching URI Syntax errors somewhere around here: https://github.com/fivefilters/readability.php/blame/master/src/Readability.php#L816

**Comment by fivefilters** [comment]
Sorry for the slow response. Should be fixed in https://github.com/fivefilters/readability.php/commit/ca965c292573302d6b5ccfd941b17f21a91e1e57. Release out soon.

**Comment by fivefilters** [comment]
Fixed in https://github.com/fivefilters/readability.php/releases/tag/v3.1.7

Thanks for reporting this.
