### ISSUE TITLE
minify html removes <html> attributes

### ISSUE THREAD

**Issue by hakkikonu** [fivefilters/readability.php#25]
When I enabled HTML minification, it removed attributes from `<html>` tag.

`<html lang="en" class="dark-mode">` -> minify -> `<html>`

Versions:

"laravel/framework": "^10.10",
 "fivefilters/readability.php": "3.1.6",

**Comment by fivefilters** [comment]
Hi there, is minification happening as part of this library or Laravel? If you could provide some code it would help us see if it's soemething we need to address or not.

**Comment by fivefilters** [comment]
Closed as there was no further info provided.
