### ISSUE TITLE
->textContent is not available

### ISSUE THREAD

**Issue by Cryental** [fivefilters/readability.php#27]
Hello.

->getContent()->textContent is not available, it's available in readability.js: 
`textContent`: text content of the article, with all the HTML tags removed;

is it possible to add this function? thank you.

**Comment by fivefilters** [comment]
Sorry for the slow reply. `getContent()` in Readability.php doesn't return an object, but the content as a string of HTML. 

To get the content as a DOM object (which will have the textContent property), you'll need to call `getDOMDocument()`.

I'm a little reluctant to change this as it's been this way for a while. Although it would be nice if it were similar to Readability.js as that's what it's based on.

But to achieve what you want, you can do this:

```
echo $readability->getDOMDocument()->textContent;
```
