### ISSUE TITLE
Deprecated: Return type of andreskrey\Readability\Nodes\NodeTrait::getAttribute($attributeName) should either be compatible with DOMElement::getAttribute(string $qualifiedName)

### ISSUE THREAD

**Issue by Dokukanal** [fivefilters/readability.php#29]
`Deprecated: Return type of andreskrey\Readability\Nodes\NodeTrait::getAttribute($attributeName) should either be compatible with DOMElement::getAttribute(string $qualifiedName): string, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/users/dokukanal/www/vendor/fivefilters/readability.php/src/Nodes/NodeTrait.php on line 172

Deprecated: Return type of andreskrey\Readability\Nodes\NodeTrait::hasAttribute($attributeName) should either be compatible with DOMElement::hasAttribute(string $qualifiedName): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/users/dokukanal/www/vendor/fivefilters/readability.php/src/Nodes/NodeTrait.php on line 190`

**Comment by fivefilters** [comment]
Hi there, thanks for the report. Can you provide some simple code to reproduce this error?

**Comment by Dokukanal** [comment]
`use andreskrey\Readability\Readability;
use andreskrey\Readability\Configuration;
use andreskrey\Readability\ParseException;`

`$descitem = $this->getReadabilityContent($entryUrl);`

`    private function getReadabilityContent($url)
    {
        $client = new Client();
        try {
            $response = $client->request('GET', $url);
            if ($response->getStatusCode() === 200) {
                $htmlContent = (string) $response->getBody();
                $readability = new Readability(new Configuration());
                $readability->parse($htmlContent);
                return $readability->getContent(); // Gibt den Hauptinhalt der Seite zurück
            }
        } catch (Exception $e) {
            // Fehlerbehandlung oder Rückgabe eines Standardtextes
            return "Inhalt konnte nicht geladen werden.";
        }
        return "Kein Inhalt verfügbar.";
    }`

**Comment by fivefilters** [comment]
This has been fixed already. See https://github.com/fivefilters/readability.php/pull/7/files#diff-bcb6d1f3b46c523f863fe12dc61cee76b8018c5a1adb0dae1dbb94fcfa97fdc2

Please upgrade the library and let us know if you still have an issue.

**Comment by Dokukanal** [comment]
@fivefilters Please look: https://github.com/fivefilters/readability.php/issues/30

**Comment by fivefilters** [comment]
The latest version we released at the time of writing is 3.1.6. You are still using an old version. If you use ^2.2 in composer, it will not install version 3. Please see https://getcomposer.org/doc/articles/versions.md#caret-version-range-

There is nothing strange here.
