### ISSUE TITLE
Namespace includes are for fivefilters in the Readme.md — but the project uses the andreskrey namespace

### ISSUE THREAD

**Issue by Dokukanal** [fivefilters/readability.php#30]
It only works like this:

```
use andreskrey\Readability\Nodes\DOM\DOMDocument;
use andreskrey\Readability\Nodes\DOM\DOMElement;
use andreskrey\Readability\Nodes\DOM\DOMNode;
```

Please check this yourself.

**Current version loaded via Composer:**
`namespace andreskrey\Readability;`
![grafik](https://github.com/fivefilters/readability.php/assets/166512533/3a6c557f-1669-4657-be67-1f6c6a2660dc)

**Comment by fivefilters** [comment]
I think you're using an old version of Readability.php. I cannot reproduce this. I suggest you try installing Readability.php with composer on a new project and see what the file looks like. This is the current version: https://github.com/fivefilters/readability.php/blob/master/src/Readability.php

**Comment by Dokukanal** [comment]
I have never used any other version before.
This version was installed as in your description and the whole thing didn't work and so I looked in the file to find the namespace.
Is it possible that some references are wrong?
I also had to adjust the namespaces like the previous speaker.
You can see the path on the screenshot.

**Comment by Dokukanal** [comment]
I have just installed it again, it is delivering the wrong files

```
./composer.json has been updated
Running composer update fivefilters/readability.php
Loading composer repositories with package information
Updating dependencies
Lock file operations: 2 installs, 0 updates, 0 removals
  - Locking fivefilters/readability.php (v2.1.0)
  - Locking psr/log (1.1.4)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing psr/log (1.1.4): Extracting archive
  - Installing fivefilters/readability.php (v2.1.0): Extracting archive
1 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
4 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
No security vulnerability advisories found.
Using version ^2.1 for fivefilters/readability.php
```

**Comment by Dokukanal** [comment]
Searching: `composer require fivefilters/readability.php:^2.2`
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires fivefilters/readability.php ^2.2, found fivefi                                       lters/readability.php[dev-ignore-tests, dev-github-actions, dev-master, dev-deve                                       lopment, v0.0.1-alpha, ..., v0.3.1, v1.0.0, v1.1.0, v1.1.1, v1.2.0, v2.0.0, v2.0                                       .1, v2.1.0, v3.0.0, ..., v3.1.6] but it does not match the constraint.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and re                                       movals for packages currently locked to specific versions.
```

Only with the following command is it possible, do you believe me now? This will "finally" install the latest version! Your versioning seems to be wrong. `php composer.phar require fivefilters/readability.php:^3.0 --with-all-dependencies`

```
./composer.json has been updated
Running composer update fivefilters/readability.php --with-all-dependencies
Loading composer repositories with package information
Updating dependencies
Lock file operations: 3 installs, 3 updates, 0 removals
  - Upgrading fivefilters/readability.php (v2.1.0 => v3.1.6)
  - Locking league/uri (6.7.2)
  - Locking league/uri-interfaces (2.3.0)
  - Locking masterminds/html5 (2.9.0)
  - Downgrading psr/http-message (2.0 => 1.1)
  - Upgrading psr/log (1.1.4 => 3.0.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 3 installs, 3 updates, 0 removals
  - Downloading masterminds/html5 (2.9.0)
  - Downloading psr/http-message (1.1)
  - Downloading league/uri-interfaces (2.3.0)
  - Downloading league/uri (6.7.2)
  - Downloading fivefilters/readability.php (v3.1.6)
  - Upgrading psr/log (1.1.4 => 3.0.0): Extracting archive
  - Installing masterminds/html5 (2.9.0): Extracting archive
  - Downgrading psr/http-message (2.0 => 1.1): Extracting archive
  - Installing league/uri-interfaces (2.3.0): Extracting archive
  - Installing league/uri (6.7.2): Extracting archive
  - Upgrading fivefilters/readability.php (v2.1.0 => v3.1.6): Extracting archive
2 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
6 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

```

![grafik](https://github.com/fivefilters/readability.php/assets/166512533/a046148c-13fc-4b1d-867f-d418252c3b2e)

**Comment by fivefilters** [comment]
There are two issues here:

1. Using `^2.2` with composer will not install the latest version of Readability, see comment here https://github.com/fivefilters/readability.php/issues/29

2. The need to use `--with-all-dependencies` is because you are trying to install Readability.php in a project which has already included some of its dependencies via other packages, and so there are version differences when you try to install Readability. You will not get this message if you install Readability.php on a new project with no other dependencies. But in any case, this is something we will fix to improve compatibility. See comment here https://github.com/fivefilters/readability.php/issues/28#issuecomment-2067636968
