### ISSUE TITLE
Implicitly Nullable Parameter in NodeTrait::hasAncestorTag()

### ISSUE THREAD

**Issue by pich** [fivefilters/readability.php#31]
I encountered a deprecation warning when using the fivefilters/readability.php library with PHP 8.4. The issue is related to a parameter in the NodeTrait::hasAncestorTag() method that is implicitly nullable but lacks an explicit nullable type declaration.

Here are the details of the warning:
PHP Deprecated:  fivefilters\Readability\Nodes\NodeTrait::hasAncestorTag(): Implicitly marking parameter $filterFn as nullable is deprecated, the explicit nullable type must be used instead in /path/to/vendor/fivefilters/readability.php/src/Nodes/NodeTrait.php on line 373

Steps to Reproduce

	1.	Use the library in a project running PHP 8.4.
	2.	Call the NodeTrait::hasAncestorTag() method with a nullable $filterFn argument.
	3.	Observe the deprecation warning.

I suggest adding the ?callable type to the $filterFn parameter in the hasAncestorTag method to explicitly mark it as nullable and comply with PHP 8.4 requirements.

**Comment by fivefilters** [comment]
Thanks @pich, will fix and release again soon. Should also add PHP 8.4 to the tests.

**Comment by fivefilters** [comment]
Fixed in [3.3.0](https://github.com/fivefilters/readability.php/releases/tag/v3.3.0)!

**Comment by pich** [comment]
@fivefilters Thanks!
